### ISSUE TITLE
在dma_ctrl中很多操作无法理解

### ISSUE THREAD

**Issue by eelykang** [flytt-away/FPGA_VIDEO_CAPTURE#1]
在dma_ctrl中有8100次传输，以及分配地址页（ALLOC_ADDR_X），等操作不结合上位机程序无法理解。作者可否提供上位机代码，以供参考！

**Comment by flytt-away** [comment]
dma一次传输16个DW的payload，上位机也采用了四帧缓存设计，所以需要分配地址页，人在外实习，电脑丢学校了0-0，上位机没法整了，建议多理解紫光给的PCIE例程，搞懂驱动的各个函数的作用

**Comment by eelykang** [comment]
> dma一次传输16个DW的payload，上位机也采用了四帧缓存设计，所以需要分配地址页，人在外实习，电脑丢学校了0-0，上位机没法整了，建议多理解紫光给的PCIE例程，搞懂驱动的各个函数的作用

好的，谢谢啦！！！
